CREATE TABLE Authors(
	AuthorID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Books(
	BookID INT PRIMARY KEY IDENTITY(1,1),
	Title NVARCHAR(200) NOT NULL,
	AuthorID INT FOREIGN KEY REFERENCES Authors(AuthorID)
);